services:
  - type: web
    name: Anormality7
    env: python
    buildCommand: |
      apt-get update && apt-get install -y python3-dev build-essential
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python3 main.py
